# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from p2sro.p2sro_manager.protobuf import (
    p2sro_manager_pb2 as p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2,
)


DESCRIPTOR = _descriptor.FileDescriptor(
    name="manager.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\rmanager.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x30p2sro/p2sro_manager/protobuf/p2sro_manager.proto"^\n\x12PolicySpecJsonList\x12\x18\n\x10policy_prob_list\x18\x01 \x03(\x02\x12.\n\x15policy_spec_json_list\x18\x02 \x03(\x0b\x32\x0f.PolicySpecJson2\x89\x06\n\x12PSRODistillManager\x12/\n\x0f\x43heckNumPlayers\x12\x0b.NumPlayers\x1a\r.Confirmation"\x00\x12\x39\n\x12GetManagerMetaData\x12\x16.google.protobuf.Empty\x1a\t.Metadata"\x00\x12.\n\tGetLogDir\x12\x16.google.protobuf.Empty\x1a\x07.String"\x00\x12K\n\x1d\x43laimNewActivePolicyForPlayer\x12\x17.NewActivePolicyRequest\x1a\x0f.PolicySpecJson"\x00\x12J\n\x1dSubmitNewActivePolicyMetadata\x12\x16.PolicyMetadataRequest\x1a\x0f.PolicySpecJson"\x00\x12\x46\n\x1e\x43\x61nActivePolicyBeSetAsFixedNow\x12\x13.PlayerAndPolicyNum\x1a\r.Confirmation"\x00\x12\x35\n\rIsPolicyFixed\x12\x13.PlayerAndPolicyNum\x1a\r.Confirmation"\x00\x12\x43\n\x16SetActivePolicyAsFixed\x12\x16.PolicyMetadataRequest\x1a\x0f.PolicySpecJson"\x00\x12\x45\n\x13GetCopyOfLatestData\x12\x16.google.protobuf.Empty\x1a\x14.P2SROStatusResponse"\x00\x12=\n\x1bSubmitEmpiricalPayoffResult\x12\r.PayoffResult\x1a\r.Confirmation"\x00\x12\x34\n\x13RequestExternalEval\x12\x0c.EvalRequest\x1a\r.Confirmation"\x00\x12>\n\x14GetDistilledMetaNash\x12\x13.PolicySpecJsonList\x1a\x0f.PolicySpecJson"\x00\x62\x06proto3',
    dependencies=[
        google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,
        p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2.DESCRIPTOR,
    ],
)


_POLICYSPECJSONLIST = _descriptor.Descriptor(
    name="PolicySpecJsonList",
    full_name="PolicySpecJsonList",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="policy_prob_list",
            full_name="PolicySpecJsonList.policy_prob_list",
            index=0,
            number=1,
            type=2,
            cpp_type=6,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="policy_spec_json_list",
            full_name="PolicySpecJsonList.policy_spec_json_list",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=96,
    serialized_end=190,
)

_POLICYSPECJSONLIST.fields_by_name[
    "policy_spec_json_list"
].message_type = (
    p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._POLICYSPECJSON
)
DESCRIPTOR.message_types_by_name["PolicySpecJsonList"] = _POLICYSPECJSONLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PolicySpecJsonList = _reflection.GeneratedProtocolMessageType(
    "PolicySpecJsonList",
    (_message.Message,),
    {
        "DESCRIPTOR": _POLICYSPECJSONLIST,
        "__module__": "manager_pb2"
        # @@protoc_insertion_point(class_scope:PolicySpecJsonList)
    },
)
_sym_db.RegisterMessage(PolicySpecJsonList)


_PSRODISTILLMANAGER = _descriptor.ServiceDescriptor(
    name="PSRODistillManager",
    full_name="PSRODistillManager",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=193,
    serialized_end=970,
    methods=[
        _descriptor.MethodDescriptor(
            name="CheckNumPlayers",
            full_name="PSRODistillManager.CheckNumPlayers",
            index=0,
            containing_service=None,
            input_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._NUMPLAYERS,
            output_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._CONFIRMATION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="GetManagerMetaData",
            full_name="PSRODistillManager.GetManagerMetaData",
            index=1,
            containing_service=None,
            input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            output_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._METADATA,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="GetLogDir",
            full_name="PSRODistillManager.GetLogDir",
            index=2,
            containing_service=None,
            input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            output_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._STRING,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="ClaimNewActivePolicyForPlayer",
            full_name="PSRODistillManager.ClaimNewActivePolicyForPlayer",
            index=3,
            containing_service=None,
            input_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._NEWACTIVEPOLICYREQUEST,
            output_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._POLICYSPECJSON,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="SubmitNewActivePolicyMetadata",
            full_name="PSRODistillManager.SubmitNewActivePolicyMetadata",
            index=4,
            containing_service=None,
            input_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._POLICYMETADATAREQUEST,
            output_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._POLICYSPECJSON,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="CanActivePolicyBeSetAsFixedNow",
            full_name="PSRODistillManager.CanActivePolicyBeSetAsFixedNow",
            index=5,
            containing_service=None,
            input_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._PLAYERANDPOLICYNUM,
            output_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._CONFIRMATION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="IsPolicyFixed",
            full_name="PSRODistillManager.IsPolicyFixed",
            index=6,
            containing_service=None,
            input_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._PLAYERANDPOLICYNUM,
            output_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._CONFIRMATION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="SetActivePolicyAsFixed",
            full_name="PSRODistillManager.SetActivePolicyAsFixed",
            index=7,
            containing_service=None,
            input_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._POLICYMETADATAREQUEST,
            output_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._POLICYSPECJSON,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="GetCopyOfLatestData",
            full_name="PSRODistillManager.GetCopyOfLatestData",
            index=8,
            containing_service=None,
            input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            output_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._P2SROSTATUSRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="SubmitEmpiricalPayoffResult",
            full_name="PSRODistillManager.SubmitEmpiricalPayoffResult",
            index=9,
            containing_service=None,
            input_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._PAYOFFRESULT,
            output_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._CONFIRMATION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="RequestExternalEval",
            full_name="PSRODistillManager.RequestExternalEval",
            index=10,
            containing_service=None,
            input_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._EVALREQUEST,
            output_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._CONFIRMATION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="GetDistilledMetaNash",
            full_name="PSRODistillManager.GetDistilledMetaNash",
            index=11,
            containing_service=None,
            input_type=_POLICYSPECJSONLIST,
            output_type=p2sro_dot_p2sro__manager_dot_protobuf_dot_p2sro__manager__pb2._POLICYSPECJSON,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_PSRODISTILLMANAGER)

DESCRIPTOR.services_by_name["PSRODistillManager"] = _PSRODISTILLMANAGER

# @@protoc_insertion_point(module_scope)
