# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import manager_pb2 as manager__pb2


class PSRODistillManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLogDir = channel.unary_unary(
            "/PSRODistillManager/GetLogDir",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=manager__pb2.PSRODistillString.FromString,
        )
        self.GetManagerMetaData = channel.unary_unary(
            "/PSRODistillManager/GetManagerMetaData",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=manager__pb2.PSRODistillMetadata.FromString,
        )
        self.ClaimNewActivePolicyForPlayer = channel.unary_unary(
            "/PSRODistillManager/ClaimNewActivePolicyForPlayer",
            request_serializer=manager__pb2.PSRODistillPlayer.SerializeToString,
            response_deserializer=manager__pb2.PSRODistillNewBestResponseParams.FromString,
        )
        self.SubmitFinalBRPolicy = channel.unary_unary(
            "/PSRODistillManager/SubmitFinalBRPolicy",
            request_serializer=manager__pb2.PSRODistillPolicyMetadataRequest.SerializeToString,
            response_deserializer=manager__pb2.PSRODistillConfirmation.FromString,
        )
        self.IsPolicyFixed = channel.unary_unary(
            "/PSRODistillManager/IsPolicyFixed",
            request_serializer=manager__pb2.PSRODistillPlayerAndPolicyNum.SerializeToString,
            response_deserializer=manager__pb2.PSRODistillConfirmation.FromString,
        )


class PSRODistillManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLogDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetManagerMetaData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ClaimNewActivePolicyForPlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SubmitFinalBRPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def IsPolicyFixed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PSRODistillManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetLogDir": grpc.unary_unary_rpc_method_handler(
            servicer.GetLogDir,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=manager__pb2.PSRODistillString.SerializeToString,
        ),
        "GetManagerMetaData": grpc.unary_unary_rpc_method_handler(
            servicer.GetManagerMetaData,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=manager__pb2.PSRODistillMetadata.SerializeToString,
        ),
        "ClaimNewActivePolicyForPlayer": grpc.unary_unary_rpc_method_handler(
            servicer.ClaimNewActivePolicyForPlayer,
            request_deserializer=manager__pb2.PSRODistillPlayer.FromString,
            response_serializer=manager__pb2.PSRODistillNewBestResponseParams.SerializeToString,
        ),
        "SubmitFinalBRPolicy": grpc.unary_unary_rpc_method_handler(
            servicer.SubmitFinalBRPolicy,
            request_deserializer=manager__pb2.PSRODistillPolicyMetadataRequest.FromString,
            response_serializer=manager__pb2.PSRODistillConfirmation.SerializeToString,
        ),
        "IsPolicyFixed": grpc.unary_unary_rpc_method_handler(
            servicer.IsPolicyFixed,
            request_deserializer=manager__pb2.PSRODistillPlayerAndPolicyNum.FromString,
            response_serializer=manager__pb2.PSRODistillConfirmation.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "PSRODistillManager", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class PSRODistillManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLogDir(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/PSRODistillManager/GetLogDir",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            manager__pb2.PSRODistillString.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetManagerMetaData(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/PSRODistillManager/GetManagerMetaData",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            manager__pb2.PSRODistillMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ClaimNewActivePolicyForPlayer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/PSRODistillManager/ClaimNewActivePolicyForPlayer",
            manager__pb2.PSRODistillPlayer.SerializeToString,
            manager__pb2.PSRODistillNewBestResponseParams.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SubmitFinalBRPolicy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/PSRODistillManager/SubmitFinalBRPolicy",
            manager__pb2.PSRODistillPolicyMetadataRequest.SerializeToString,
            manager__pb2.PSRODistillConfirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def IsPolicyFixed(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/PSRODistillManager/IsPolicyFixed",
            manager__pb2.PSRODistillPlayerAndPolicyNum.SerializeToString,
            manager__pb2.PSRODistillConfirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
